'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class EditarCurso

    '''<summary>
    '''CodigoCurso control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CodigoCurso As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''NomeCurso control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NomeCurso As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''SiglaCurso control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SiglaCurso As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''ValorCreditoCurso control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ValorCreditoCurso As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''Editar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Editar As Global.System.Web.UI.WebControls.Button
End Class
